"""Extract wavelet filter coefficients from pywt and generate _filters.py."""
import pywt

families = {
    'haar': ['haar'],
    'db': [f'db{i}' for i in range(1, 21)],
    'sym': [f'sym{i}' for i in range(2, 21)],
    'coif': [f'coif{i}' for i in range(1, 6)],
}

wavelets = [name for names in families.values() for name in names]

lines = [
    '"""Wavelet filter coefficients. Auto-generated by scripts/extract_filters.py."""',
    '',
    'FILTER_BANKS = {',
]

for name in wavelets:
    w = pywt.Wavelet(name)
    dec_lo, dec_hi, rec_lo, rec_hi = w.filter_bank
    lines.append(f'    {name!r}: (')
    lines.append(f'        {tuple(dec_lo)},')
    lines.append(f'        {tuple(dec_hi)},')
    lines.append(f'        {tuple(rec_lo)},')
    lines.append(f'        {tuple(rec_hi)},')
    lines.append(f'    ),')

lines.append('}')
lines.append('')

print('\n'.join(lines))
